-- Sistema de Controle de Voluntarios ELLP
-- Execute este arquivo no Query Tool do pgAdmin dentro do banco desejado.
-- Ele cria a estrutura necessaria para a versao atual do sistema.
-- Para criar um banco novo, execute primeiro, conectado ao banco "postgres":
-- CREATE DATABASE ellp_db;
-- Depois abra o Query Tool do banco "ellp_db" e execute o restante deste arquivo.

BEGIN;

CREATE TABLE IF NOT EXISTS coordenadores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  login VARCHAR(100) NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS sintese (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cronograma (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  descricao TEXT NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  meses JSON NOT NULL DEFAULT '[]'::json,
  CONSTRAINT cronograma_datas_validas CHECK (data_fim >= data_inicio)
);

CREATE TABLE IF NOT EXISTS voluntario (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  sintese_id INTEGER REFERENCES sintese(id) ON DELETE SET NULL,
  cronograma_id INTEGER REFERENCES cronograma(id) ON DELETE SET NULL,
  data_nascimento DATE NOT NULL,
  nacionalidade VARCHAR(100) NOT NULL,
  estudante VARCHAR(10) NOT NULL,
  curso VARCHAR(150) NOT NULL,
  periodo INTEGER NOT NULL,
  ra VARCHAR(20) NOT NULL,
  endereco VARCHAR(255) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(100) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT voluntario_periodo_valido CHECK (periodo BETWEEN 1 AND 12),
  CONSTRAINT voluntario_data_nascimento_valida
    CHECK (data_nascimento >= DATE '1900-01-01' AND data_nascimento <= CURRENT_DATE)
);

CREATE UNIQUE INDEX IF NOT EXISTS coordenadores_login_unique
  ON coordenadores (LOWER(login));

CREATE UNIQUE INDEX IF NOT EXISTS voluntario_cpf_unique
  ON voluntario (REGEXP_REPLACE(cpf, '[^0-9]', '', 'g'));

CREATE UNIQUE INDEX IF NOT EXISTS voluntario_ra_unique
  ON voluntario (ra);

CREATE UNIQUE INDEX IF NOT EXISTS voluntario_email_unique
  ON voluntario (LOWER(email));

CREATE INDEX IF NOT EXISTS voluntario_cronograma_id_idx
  ON voluntario (cronograma_id);

CREATE INDEX IF NOT EXISTS voluntario_sintese_id_idx
  ON voluntario (sintese_id);

COMMIT;

-- Crie o primeiro coordenador trocando os valores abaixo e removendo os sinais de comentario:
-- INSERT INTO coordenadores (nome, login, senha)
-- VALUES ('Administrador', 'admin', 'troque-esta-senha');
--
-- A versao atual ainda armazena senhas sem criptografia.
-- A proxima melhoria recomendada e usar bcrypt no cadastro e no login.
