-- Sistema de Controle de Voluntarios ELLP
-- Execute este arquivo no Query Tool do pgAdmin dentro do banco desejado.
-- Ele cria a estrutura necessaria para a versao atual do sistema.
-- Para criar um banco novo, execute primeiro, conectado ao banco "postgres":
-- CREATE DATABASE ellp_db;
-- Depois abra o Query Tool do banco "ellp_db" e execute o restante deste arquivo.

BEGIN;

CREATE TABLE IF NOT EXISTS coordenadores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  login VARCHAR(100) NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS sintese (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cronograma (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  descricao TEXT NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  meses JSON NOT NULL DEFAULT '[]'::json,
  CONSTRAINT cronograma_datas_validas CHECK (data_fim >= data_inicio)
);

CREATE TABLE IF NOT EXISTS voluntario (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  sintese_id INTEGER REFERENCES sintese(id) ON DELETE SET NULL,
  cronograma_id INTEGER REFERENCES cronograma(id) ON DELETE SET NULL,
  data_nascimento DATE NOT NULL,
  nacionalidade VARCHAR(100) NOT NULL,
  estudante VARCHAR(10) NOT NULL,
  curso VARCHAR(150) NOT NULL,
  periodo INTEGER NOT NULL,
  ra VARCHAR(20) NOT NULL,
  endereco VARCHAR(255) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(100) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT voluntario_cpf_valido
    CHECK (LENGTH(REGEXP_REPLACE(cpf, '[^0-9]', '', 'g')) = 11),
  CONSTRAINT voluntario_telefone_valido
    CHECK (LENGTH(REGEXP_REPLACE(telefone, '[^0-9]', '', 'g')) BETWEEN 10 AND 11),
  CONSTRAINT voluntario_ra_valido
    CHECK (ra ~ '^[0-9]{4,12}$'),
  CONSTRAINT voluntario_email_valido
    CHECK (email LIKE '%_@_%._%'),
  CONSTRAINT voluntario_estudante_valido
    CHECK (LOWER(estudante) IN ('sim', 'nao')),
  CONSTRAINT voluntario_periodo_valido CHECK (periodo BETWEEN 1 AND 12),
  CONSTRAINT voluntario_data_nascimento_valida
    CHECK (data_nascimento >= DATE '1900-01-01')
);

CREATE TABLE IF NOT EXISTS auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coordenador_id INTEGER REFERENCES coordenadores(id) ON DELETE SET NULL,
  coordenador_nome VARCHAR(150) NOT NULL,
  acao VARCHAR(30) NOT NULL,
  entidade VARCHAR(50) NOT NULL,
  entidade_id INTEGER,
  detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
  criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS coordenadores_login_unique
  ON coordenadores (LOWER(login));

CREATE UNIQUE INDEX IF NOT EXISTS voluntario_cpf_unique
  ON voluntario (REGEXP_REPLACE(cpf, '[^0-9]', '', 'g'));

CREATE UNIQUE INDEX IF NOT EXISTS voluntario_ra_unique
  ON voluntario (ra);

CREATE UNIQUE INDEX IF NOT EXISTS voluntario_email_unique
  ON voluntario (LOWER(email));

CREATE INDEX IF NOT EXISTS voluntario_cronograma_id_idx
  ON voluntario (cronograma_id);

CREATE INDEX IF NOT EXISTS voluntario_sintese_id_idx
  ON voluntario (sintese_id);

CREATE INDEX IF NOT EXISTS auditoria_criado_em_idx
  ON auditoria (criado_em DESC);

CREATE INDEX IF NOT EXISTS auditoria_entidade_idx
  ON auditoria (entidade, entidade_id);

INSERT INTO coordenadores (nome, login, senha)
SELECT
  'Administrador',
  'admin',
  '$2b$12$lAtMJTuf/lqmpACAdAifV.WaNTbCzbNl6bOHBxwF5CnY1Je3otwyy'
WHERE NOT EXISTS (
  SELECT 1
  FROM coordenadores
  WHERE LOWER(login) = 'admin'
);

UPDATE coordenadores
SET senha = '$2b$12$lAtMJTuf/lqmpACAdAifV.WaNTbCzbNl6bOHBxwF5CnY1Je3otwyy'
WHERE LOWER(login) = 'admin'
  AND senha = 'admin123';

COMMIT;

-- Primeiro acesso: login admin / senha admin123
-- Troque a senha depois do primeiro acesso.
-- As senhas sao armazenadas com hash bcrypt.
